"""Add tech_used to Project model

Revision ID: 2f3de5400f77
Revises: 9a4c4f8b14da
Create Date: 2024-09-03 11:56:36.497364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3de5400f77'
down_revision = '9a4c4f8b14da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_used', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tech_used')

    # ### end Alembic commands ###
