"""Change project images to database storage

Revision ID: 92039fffc27a
Revises: b9a9af8e7601
Create Date: 2025-05-23 17:42:24.117396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92039fffc27a'
down_revision = 'b9a9af8e7601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_demo_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('blog_post_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_image_mimetype', sa.String(length=100), nullable=True))
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('cover_image_mimetype')
        batch_op.drop_column('cover_image_filename')
        batch_op.drop_column('cover_image_data')
        batch_op.drop_column('blog_post_link')
        batch_op.drop_column('youtube_link')
        batch_op.drop_column('live_demo_link')

    # ### end Alembic commands ###
