"""Add new fields to Project model

Revision ID: 964f5a11bc3e
Revises: d55e3d6516ae
Create Date: 2024-09-09 21:23:39.114643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964f5a11bc3e'
down_revision = 'd55e3d6516ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('description_html')

    # ### end Alembic commands ###
