"""Add new columns to Project model

Revision ID: 9830aadde9eb
Revises: c2ce4cc747c2
Create Date: 2024-09-03 10:47:45.328261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9830aadde9eb'
down_revision = 'c2ce4cc747c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('project_files_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('research_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('cover_image')
        batch_op.drop_column('research_link')
        batch_op.drop_column('project_files_link')
        batch_op.drop_column('twitter_link')
        batch_op.drop_column('github_link')

    # ### end Alembic commands ###
