"""Add additional indexes and relationships for performance

Revision ID: addf42f8a453
Revises: b60e86e0d784
Create Date: 2025-05-23 18:00:26.479636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addf42f8a453'
down_revision = 'b60e86e0d784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_title'), ['title'], unique=False)

    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_title'))
        batch_op.drop_index(batch_op.f('ix_research_is_archived'))
        batch_op.drop_index(batch_op.f('ix_research_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_author_id'))

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_title'))
        batch_op.drop_index(batch_op.f('ix_dataset_is_archived'))
        batch_op.drop_index(batch_op.f('ix_dataset_created_at'))
        batch_op.drop_index(batch_op.f('ix_dataset_author_id'))

    # ### end Alembic commands ###
