"""Add indexes for performance optimization

Revision ID: b60e86e0d784
Revises: 92039fffc27a
Create Date: 2025-05-23 17:56:07.391488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60e86e0d784'
down_revision = '92039fffc27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_title'), ['title'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_title'))
        batch_op.drop_index(batch_op.f('ix_project_is_archived'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))
        batch_op.drop_index(batch_op.f('ix_project_author_id'))

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_title'))
        batch_op.drop_index(batch_op.f('ix_blog_is_archived'))
        batch_op.drop_index(batch_op.f('ix_blog_created_at'))
        batch_op.drop_index(batch_op.f('ix_blog_author_id'))

    # ### end Alembic commands ###
