"""Add mermaid_chart to Project model

Revision ID: b9a9af8e7601
Revises: 964f5a11bc3e
Create Date: 2024-09-18 16:06:23.411561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a9af8e7601'
down_revision = '964f5a11bc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mermaid_chart', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('mermaid_chart')

    # ### end Alembic commands ###
