"""Add awards and achievements to Project model

Revision ID: d55e3d6516ae
Revises: 2f3de5400f77
Create Date: 2024-09-09 10:56:15.956909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55e3d6516ae'
down_revision = '2f3de5400f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awards', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('achievements')
        batch_op.drop_column('awards')

    # ### end Alembic commands ###
