"""Add is_archived to Blog and Project

Revision ID: def51c877124
Revises: 24eec1c2b288
Create Date: 2024-09-03 09:59:42.630772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def51c877124'
down_revision = '24eec1c2b288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
